### ISSUE TITLE
[Bug] Embedded config is not being parse correctly 

### ISSUE THREAD

**Issue by dohernandez** [g4s8/envdoc#29]
# Describe the bug

- [ ] Documentation is not generated when the struct has been embedded. #32
- [x] Documentation is not generated when the field does not have the tag `env` #30
- [x] Documentation is not generated when the default tag is customised. #30

## To reproduce

```
type Job struct {
	// Name is the name of the job.
	Name string `env:"NAME,required,notEmpty"`
	// Enable is to enable of the job.
	Enable bool `default:"true"`
}

type Environment struct {
	slug string
}

type Base struct {
	// Environment is the environment the application is running in.
	Environment Environment `env:"ENVIRONMENT" default:"live"`
}

type Log struct {
	// Level is the log level.
	Level zapcore.Level `default:"error"`
}

//go:generate envdoc -output config.md -types Config
type Config struct {
	Base
	Job
	
	// Log is the log configuration.
	Log Log `envPrefix:"LOG_"`
}

envOpts := env.Options{
	DefaultValueTagName:   "default",
	UseFieldNameByDefault: true,
}
```

### Ouput

```
# Environment Variables

## Config
```

### Expected Output

```
# Environment Variables

## Config

- `ENVIRONMENT` (default: `live`) - Environment is the environment the application is running in.
- `NAME` (**required**, non-empty) - Name is the name of the job.
- `ENABLE` (default: `true`) - Enable is to enable the job.
- `LOG_LEVEL`  (default: `error`) - Environment is the environment the application is running in.
```

**Comment by g4s8** [comment]
The problem should be fixed. I've introduced options to specify custom tag names:
 - `-tag-name` - to change `env:` tag name
 - `-tag-default` to change `envDefault:` tag name

And fixed the problem with embedded fields.

Also, in your case you can use `-field-names` option to generate documentation without tags.

Your example (with modified go gen dir):
```go
package main

import "go.uber.org/zap/zapcore"

type Job struct {
	// Name is the name of the job.
	Name string `env:"NAME,required,notEmpty"`
	// Enable is to enable of the job.
	Enable bool `default:"true"`
}

type Environment struct {
	slug string
}

type Base struct {
	// Environment is the environment the application is running in.
	Environment Environment `env:"ENVIRONMENT" default:"live"`
}

type Log struct {
	// Level is the log level.
	Level zapcore.Level `default:"error"`
}

//go:generate go run ../.. -output doc.md -types Config -field-names -tag-default default
type Config struct {
	Base
	Job

	// Log is the log configuration.
	Log Log `envPrefix:"LOG_"`
}
```

And generated documentation:
```md
# Environment Variables

## Config

 - `ENVIRONMENT` (default: `live`) - Environment is the environment the application is running in.
 - `NAME` (**required**, non-empty) - Name is the name of the job.
 - `ENABLE` (default: `true`) - Enable is to enable of the job.
 - `LOG` - Log is the log configuration.
   - `LOG_LEVEL` (default: `error`) - Level is the log level.
```

Changes will be available in the next release. Thanks for reporting.

**Comment by g4s8** [comment]
Release with new fixes: https://github.com/g4s8/envdoc/releases/tag/v1.1.0
